# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task --list-all

  build:
    cmds:
      - cargo build

  run:
    cmds:
      - cargo run

  format:
    cmds:
      - cargo fmt --all

  test:
    cmds:
      - cargo test

  coverage:
    cmds:
      - cargo tarpaulin

  lint:
    cmds:
      - cargo clippy

  install:
    cmds:
      - cargo fetch

  db:migrate:
    desc: "Run sql migration files against database"
    cmds:
      - sqlx migrate run
