# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task --list-all

  build:
    cmds:
      - cargo build

  run:
    cmds:
      - cargo run

  format:
    cmds:
      - cargo fmt --all
  
  lint:
    cmds:
      - cargo clippy

  test:
    cmds:
      - task: db:reset
      - cargo test --lib

  test:integration:
    cmds:
      - task: db:reset
      - cargo test --lib -- --ignored

  coverage:
    cmds:
      - task: db:reset
      - cargo tarpaulin --lib

  lint:
    cmds:
      - cargo clippy

  install:
    cmds:
      - cargo fetch

  db:migrate:
    desc: "Run sql migration files against database"
    cmds:
      - cargo sqlx migrate run

  db:reset:
    desc: "Wipes and migrates the database"
    cmds:
      - cargo sqlx database reset -yf
